version: '3.8'
services:
  db:
    image: ankane/pgvector:latest
    container_name: our_planet_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: wzhpxy2026
      POSTGRES_DB: our_planet
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: